inherit_gem:
  betterlint:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - gemfiles/*.gemfile

Gemspec/DevelopmentDependencies:
  Enabled: false
